version: '3.9'

services:
  web:
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "api.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: redis:alpine
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
