# Generated by Django 4.2 on 2024-12-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
